import type { Metadata } from "next";

import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import { Inter } from 'next/font/google'
import Header from "@/components/header";
import Footer from "@/components/footer";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.min.css' 
const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
       <body className={inter.className}>
        <div className="mobile-only"> 
        <Header />
       <div className="magin-body mb-5"> {children}</div>
       <div className="mt-5"> <Footer /></div>
       <ToastContainer position="top-right"
    autoClose={5000}
    hideProgressBar={false}
    newestOnTop={false}
    closeOnClick
    rtl={false}
    pauseOnFocusLoss
    draggable
    pauseOnHover
    theme="light"/>  
        </div>
      </body>
    </html>
  );
}
